name: Maven

on:
  push:
  pull_request:

jobs:
  build:
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Shallow clones should be disabled for a better relevancy of SonarQube analysis
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages. 
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
          ~/.sonar/cache
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Set Maven Additional Goals
      run: |
        echo "SONARGOAL=sonar:sonar" >> $GITHUB_ENV
      if: ${{ env.SONAR_TOKEN }}
    - name: Build with Maven and SonarCloud
      run: >
        xvfb-run mvn test -Pjacoco $SONARGOAL
        -Dsonar.organization=lorenzobettini-github
        -Dsonar.host.url=https://sonarcloud.io
      working-directory: com.examples.school
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Store Build
      uses: actions/upload-artifact@v2
      with:
        name: pr
        path: ./
      if: ${{ env.SONAR_TOKEN == '' }}
